<?php 
$_SETTINGS=['_MODULES'=>[
	'mulgach'=>[],
	'mulgach.hmvc'=>array(),
	'db'=>array(),	
	'jquery'=>array(),
	'jquery.ui'=>[],
	'bootstrap'=>array(),
	'route'=>array(),
	'captcha'=>array(),
	'archive'=>array(),
]];
?>