<?php
$_DATA=array(
	array('url'=>'?r=bykva','capt'=>'#{bykva}'),
		array('url'=>'?r=kursy','capt'=>'#{kursy}'),
		array('url'=>'?r=lifearea','capt'=>'#{lifearea}'),
		array('url'=>'?r=predlogenie','capt'=>'#{predlogenie}'),
		array('url'=>'?r=preps','capt'=>'#{preps}'),
		array('url'=>'?r=primeneniye','capt'=>'#{primeneniye}'),
		array('url'=>'?r=razdel','capt'=>'#{razdel}'),
		array('url'=>'?r=slog','capt'=>'#{slog}'),
		array('url'=>'?r=slovo','capt'=>'#{slovo}'),
		array('url'=>'?r=student','capt'=>'#{student}'),
		array('url'=>'?r=ucheba','capt'=>'#{ucheba}'),
		array('url'=>'?r=urok','capt'=>'#{urok}'),
		array('url'=>'?r=users','capt'=>'#{users}'),
		array('url'=>'?r=zadanie','capt'=>'#{zadanie}'),
		array('url'=>'?r=znak','capt'=>'#{znak}'),
	);