<?php
$_DATA=array(
	array('url'=>'bykva','capt'=>'#{bykva}'),
		array('url'=>'kursy','capt'=>'#{kursy}'),
		array('url'=>'lifearea','capt'=>'#{lifearea}'),
		array('url'=>'predlogenie','capt'=>'#{predlogenie}'),
		array('url'=>'preps','capt'=>'#{preps}'),
		array('url'=>'primeneniye','capt'=>'#{primeneniye}'),
		array('url'=>'razdel','capt'=>'#{razdel}'),
		array('url'=>'slog','capt'=>'#{slog}'),
		array('url'=>'slovo','capt'=>'#{slovo}'),
		array('url'=>'student','capt'=>'#{student}'),
		array('url'=>'ucheba','capt'=>'#{ucheba}'),
		array('url'=>'urok','capt'=>'#{urok}'),
		array('url'=>'users','capt'=>'#{users}'),
		array('url'=>'zadanie','capt'=>'#{zadanie}'),
		array('url'=>'znak','capt'=>'#{znak}'),
	);