<?php
$_DATA=array(
	array('url'=>'?r=kursy','capt'=>'#{kursy}'),
		array('url'=>'?r=preps','capt'=>'#{preps}'),
		array('url'=>'?r=razdel','capt'=>'#{razdel}'),
		array('url'=>'?r=urok','capt'=>'#{urok}'),
		array('url'=>'?r=users','capt'=>'#{users}'),
		array('url'=>'?r=zadanie','capt'=>'#{zadanie}'),
	);